/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uk.ac.bradford.mfa.gui;

import uk.ac.bradford.mfa.LoginManager;
import uk.ac.bradford.mfa.MFAStrategy;

/**
 *
 * @author maxim
 */
public class MfaSelectionGui extends javax.swing.JFrame {

    private LoginManager manager;

    /**
     * Creates new form MfaSelectionGui
     */
    public MfaSelectionGui(LoginManager manager) {
        this.manager = manager; // Now this screen shares the same logic
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboMfaMethod = new javax.swing.JComboBox<>();
        btnContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose a verification method:");

        comboMfaMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email", "Authenticator App", " " }));

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContinue)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboMfaMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMfaMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnContinue)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
        String selection = comboMfaMethod.getSelectedItem().toString();
        MFAStrategy selectedStrategy;

        if (selection.equals("Email")) {
            selectedStrategy = new uk.ac.bradford.mfa.EmailAuthenticator();
            // Trigger the real email send
            selectedStrategy.sendCode("your_email@example.com");
        } else {
            selectedStrategy = new uk.ac.bradford.mfa.TOTPAuthenticator();
            selectedStrategy.sendCode(null); // TOTP doesn't need a destination
        }

        manager.setMfaMethod(selectedStrategy);

        // Show the input dialog AFTER sending the code
        String inputCode = javax.swing.JOptionPane.showInputDialog(this,
                "A verification code has been sent via " + selection + ".\nPlease enter the 6-digit code:");

        if (manager.verifyMFA(inputCode)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Access Granted! Welcome to University Systems.");
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Code.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContinueActionPerformed

/**
 * @param args the command line arguments
 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JComboBox<String> comboMfaMethod;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
